server:
  log_level: debug
logs:
  # Choose a directory to save the last read position of log files at.
  # This directory will be created if it doesn't already exist.
  positions_directory: "C:\\Windows\\System32\\winevt\\Logs"
  configs:
    - name: windows
      # Loki endpoint to push logs to
      clients:
        - url: http://loki.private.acmpocdns.com/loki/api/v1/push
      scrape_configs:
      - job_name: windows
        windows_events:
          # Note the directory structure must already exist but the file will be created on demand
          bookmark_path: "C:\\opt\\bookmark\\bookmark.xml"
          use_incoming_timestamp: false
          log_type: "Application"
          # Filter for logs
          xpath_query: '*'
          labels:
            log_type: application
            vm: windows-vm